### PR TITLE
Fix locale data and improve locale resolving

### LINKED ISSUE #25: RelativeFormat.__localeData__ needs the full locale name, instead we just take the root locale
https://github.com/yahoo/intl-relativeformat/blob/master/src/core.js#L69

I believe is going to cause an issue as well for https://github.com/yahoo/react-intl/issues/78

Steps:
* Load both parsed CLDR objects into `IntlRelativeTime.__addLocaleData`
* The following will output the same:
  * `new IntlRelativeFormat('zh-hant-tw').format(new Date(new Date() - 3 * 60000));`
  * `new IntlRelativeFormat('zh').format(new Date(new Date() - 3 * 60000));`

### PR DESCRIPTION
**Pull request by ericf**
This upgrades to `intl-messageformat@1.1.0` and `grunt-extract-cldr-data@2.1.1` which vastly improves the locale data in the following ways:

* Added locale data for all leaf locales which differ from their root locale's data; e.g. `zh-Hant-HK` is not the same as `zh-Hant` which is not the same as `zh`.

* Properly de-duplicate data for all CLDR locales by correctly traversing a locale's hierarchy of ancestor locales.

* Added data for the following languages:
  aa, agq, bas, bh, ckb, dav, dje, dsb, dua, dv, dyo, ebu, ewo, guw, guz, hsb, ia, in, iu, iw, jbo, ji, jv, jw, kaj, kam, kcg, khq, ki, kln, kok, ksf, ku, lb, lu, luo, luy, mer, mfe, mgh, mo, mua, nah, nmg, no, nqo, nus, ny, pap, prg, qu, rn, rw, sbp, sh, sma, smi, smj, smn, sms, swc, syr, tk, tl, twq, vai, wa, wo, yav, yi, zgh

----

These changes also include improvements for how locales are resolved. Here are some details of these changes:

* If no extra locale data is loaded, the locale will _always_ resolved to `en`.

* If locale data is missing for a leaf locale like `fr-FR`, but there _is_ data for the root, `fr` in this case, then its root will be used.

* If there's data for the specified locale, then that locale will be resolved; i.e.,

    ```js
    var rf = new IntlRelativeFormat('en-US');
    assert(rf.resolvedOptions().locale === 'en-US'); // true
    ```

* The resolved locales are now normalized; e.g., `en-us` will resolve to: `en-US`.

Fixes #25

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ericf** [comment]
After this is merged the README docs should be updated.

**Comment by caridy** [comment]
:8ball:

**Comment by jasonmit** [comment]
:shipit:

**Pull request merged**
